# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "1.12.2" ]
  pull_request:
    branches: [ "1.12.2" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DL_URL: https://github.com/KELETU66666/GT5-Unofficial/archive/refs/heads/1.12.2.zip
      Pack_Name: 1.12.2
      Open_Pack_Name: GT5-Unofficial-1.12.2
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK 11
      uses: actions/setup-java@v3.3.0
      with: 
        java-version: '11'
        distribution: 'temurin'
        java-package: jdk
    - name: Setup Java JDK 18
      uses: actions/setup-java@v3.3.0
      with: 
        java-version: '18'
        distribution: 'temurin'
        java-package: jdk
    - name: Setup Java JDK 8
      uses: actions/setup-java@v3.3.0
      with: 
        java-version: '8'
        distribution: 'temurin'
        java-package: jdk
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: output
        path: /opt/libs/
