# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "1.12.2" ]
  pull_request:
    branches: [ "1.12.2" ]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: ".gradlew"
          generate-job-summary: false

      - name: Get Current Mod Version
        id: get_current_version
        run: echo ::set-output name=version::$(./gradlew getVersionFromJava --q)

      - name: Get Mod Version without Extra
        id: get_version_no_extra
        run: echo ::set-output name=version::$(echo "$(./gradlew getVersionFromJava --q | sed -E 's/1.12.2-|-.+//g')")

      - name: Retrieve Jar from Latest Release
        run: wget "https://github.com/${{ github.repository }}/releases/download/v${{ steps.get_version_no_extra.outputs.version }}/gregtech-1.12.2-${{ steps.get_current_version.outputs.version }}.jar"

      - name: Create CurseForge Release
        uses: itsmeow/curseforge-upload@v3
        with:
          game_versions: "Minecraft 1.12:1.12.2,Java 8,Forge"
          game_endpoint: "minecraft"
          release_type: "beta"
          changelog: "Changelog is available [here](https://github.com/${{ github.repository }}/releases/tag/v${{ steps.get_version_no_extra.outputs.version }})."
          changelog_type: "markdown"
          relations: "codechicken-lib-1-8:requiredDependency,gregtechce:incompatible,gregtech-chill-edition:incompatible"
          file_path: "gregtech-1.12.2-${{ steps.get_current_version.outputs.version }}.jar"
          project_id: "${{ secrets.CURSEFORGE_PROJECT_ID }}"
          token: "${{ secrets.CURSEFORGE_API_KEY }}"
